### ISSUE TITLE
5.0.0 declares maven-jar-plugin:3.0.0 that does not exist. 

### ISSUE THREAD

**Issue by ssaarinen** [simpligility/progressive-organization-pom#23]
[Maven central](http://search.maven.org/#search|ga|1|g%3A%22org.apache.maven.plugins%22%20AND%20a%3A%22maven-jar-plugin%22) suggests 2.6 so where is this 3.0.0 coming from?

**Comment by mosabua** [comment]
It leaked in from the staging repositories and is now available.
