### ISSUE TITLE
inheriting the release profile can break mvn release:perform

### ISSUE THREAD

**Issue by rtack** [simpligility/progressive-organization-pom#25]
After adding the progressive-organization pom as parent, mvn release:perform would fail with

--- maven-gpg-plugin:1.6:sign (default) @ parent ---
[INFO] gpg: no default secret key: No secret key
[INFO] gpg: signing failed: No secret key

 [INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (default) on project parent: Exit code: 2 -> [Help 1]

Could 
```
<plugin>
      <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
```
be changed to add
```
<inherited>false</inherited> 
```

or what would other ways be to not have the unwanted behaviour?

e.g. we don't use the maven-gpg-plugin in our build.

**Comment by rtack** [comment]
For the moment I've solved it with 
```
<plugin>
         <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5.1</version>
                <configuration>
                    <arguments>-Dgpg.skip=true</arguments>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                </configuration>
    </plugin>
```
but still thinking that the gpg sign should not be inherited

**Comment by mosabua** [comment]
Do you know if inherited set to false can be overridden to true again? All the consuming projects I am working with are releasing to the Central Repository and need gpg as part of the release... so if I take it out I have to put it back in again. 

If you skip it like you do above thats a good idea imho. Just take the version out of the config..

**Comment by rtack** [comment]
so there is a usecase for inheriting it. skipping it works fine. don't think you can override it to true again. will close this issue.
