### ISSUE TITLE
how to control distribution management in child POMs?

### ISSUE THREAD

**Issue by Kortanul** [simpligility/progressive-organization-pom#26]
when trying to deploy artifacts that use this POM as their parent, Maven always tries to deploy to Maven Central instead of to our local Maven artifactory. how do we override the `<distributionManagement>` settings in this parent POM?

**Comment by Kortanul** [comment]
answered my own question: you should just be able to define a new `<distributionManagement>` section in the child POM.

what threw me off is that our project is actually a fork of another project, and that project pulls in an intermediate POM (`org.simplify4u:parent-root:2.3.0`) that forcibly causes child POMs to inherit an execution of the `nexus-staging-maven-plugin`. That execution forces the `ossrh` repo specified under distribution management to be used no matter what the child POM provides.

I was able to disable it via:
```
<build>
  <plugins>
    <plugin>
      <!-- Disable Sonatype Nexus Extensions for Wren Security's Repo -->
      <groupId>org.sonatype.plugins</groupId>
      <artifactId>nexus-staging-maven-plugin</artifactId>
      <extensions>false</extensions>
      <executions>
        <execution>
          <id>injected-nexus-deploy</id>
          <phase>none</phase>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
```

but that has nothing to do with this parent POM project, so I will close this.

**Comment by mosabua** [comment]
Correct. So you could make your own company pom by inherting from this project and overriding what you need to be specific to your company..
